version: '3.8'

services:
  witnesses:
    build:
      context: ./images
      dockerfile: witnesses.dockerfile

  vlei-server:
    build:
      context: ./images
      dockerfile: vlei.dockerfile

  keria:
    build:
      context: ./images
      dockerfile: keria.dockerfile
    depends_on:
      - witnesses

  server:
    build:
      context: ./images
      dockerfile: server.dockerfile

  webapp:
    build:
      context: ./images
      dockerfile: webapp.dockerfile

  verifier:
    build:
      context: ./images
      dockerfile: verifier.dockerfile
    depends_on:
      - witnesses
