version: '3.8'

networks:
  reg:
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  witnesses:
    build:
      context: ./images
      dockerfile: witnesses.dockerfile
    ports:
      - 5632:5632
      - 5633:5633
      - 5634:5634
      - 5642:5642
      - 5643:5643
      - 5644:5644
    networks:
      reg:
        ipv4_address: 172.20.0.10
    volumes:
      - './data/keri:/usr/local/var/keri/'

  vlei-server:
    build:
      context: ./images
      dockerfile: vlei.dockerfile
    ports:
      - 7723:7723
    networks:
      reg:
        ipv4_address: 172.20.0.20

  keria:
    build:
      context: ./images
      dockerfile: keria.dockerfile
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903
    depends_on:
      - witnesses
    networks:
      reg:
        ipv4_address: 172.20.0.30
    volumes:
      - './data/keri:/usr/local/var/keri/'

  # webapp:
  #   build:
  #     context: ./images
  #     dockerfile: webapp.dockerfile
  #   ports:
  #     - 5173:5173
  #   networks:
  #     - reg

  # verifier:
  #   build:
  #     context: ./images
  #     dockerfile: verifier.dockerfile
  #   depends_on:
  #     - witnesses
  #   networks:
  #     - reg
  #   volumes:
  #     - './data/keri:/usr/local/var/keri'

  # server:
  #   build:
  #     context: ./images
  #     dockerfile: server.dockerfile
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #     - VERIFIER_AUTHORIZATIONS=http://verifier:7676/authorizations/
  #     - VERIFIER_PRESENTATIONS=http://verifier:7676/presentations/
  #     - VERIFIER_REPORTS=http://verifier:7676/reports/
  #   depends_on:
  #     - redis
  #   networks:
  #     - reg

  # celery:
  #   build:
  #     context: ./images
  #     dockerfile: server.dockerfile
  #   environment:
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - server
  #     - redis
  #   networks:
  #     - reg

  # redis:
  #   image: redis:7-alpine
  #   networks:
  #     - reg
