version: '3.8'

networks:
  reg:

services:
  build-keripy:
    build: 
      context: https://github.com/tibor19/keripy.git#dockerfile
    image: build-keripy

  witnesses:
    build:
      context: ./images
      dockerfile: witnesses.dockerfile
    ports:
      - 5632:5632
      - 5633:5633
      - 5634:5634
      - 5642:5642
      - 5643:5643
      - 5644:5644
    networks:
      - reg
    volumes:
      - './data/keri:/usr/local/var/keri/'

  vlei:
    build:
      context: ./images
      dockerfile: vlei.dockerfile
    ports:
      - 7723:7723
    networks:
      - reg

  keria:
    build:
      context: https://github.com/tibor19/keria.git#dockerfile
    ports:
      - 3901:3901
      - 3902:3902
      - 3903:3903
    depends_on:
      - witnesses
      - build-keripy
    networks:
      - reg
    volumes:
      - './data/keri:/usr/local/var/keri/'

  verifier:
    build:
      context: ./images
      dockerfile: verifier.dockerfile
    depends_on:
      - witnesses
    ports:
      - 7676:7676
    networks:
      - reg
    volumes:
      - './data/keri:/usr/local/var/keri'

  redis:
    image: redis:7-alpine
    networks:
      - reg

  celery:
    build: 
      context: https://github.com/tibor19/reg-poc-server.git#dockerfile
      dockerfile: celery.Dockerfile
    depends_on:
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - VERIFIER_AUTHORIZATIONS=http://verifier:7676/authorizations/
      - VERIFIER_PRESENTATIONS=http://verifier:7676/presentations/
      - VERIFIER_REPORTS=http://verifier:7676/reports/
    networks:
      - reg

  server:
    build:
      context: https://github.com/tibor19/reg-poc-server.git#dockerfile
      dockerfile: server.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - celery
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - ENABLE_CORS=true
      - VERIFIER_AUTHORIZATIONS=http://verifier:7676/authorizations/
      - VERIFIER_PRESENTATIONS=http://verifier:7676/presentations/
      - VERIFIER_REPORTS=http://verifier:7676/reports/
    networks:
      - reg

  webapp:
    build: 
      context: https://github.com/tibor19/reg-poc-webapp.git#dockerfile
    ports:
      - 5173:5173
    depends_on:
      - server
    networks:
      - reg